site_name: Fairification Framework
nav:
  - Architecture: architecture.md
theme:
  name: material

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true