site_name: Fairification Framework
nav:
  - Architecture: architecture.md
  - Services: 
    - Getting Started: services/getting-started.md
    - FAIR Assessment: services/ff-assessment.md
theme:
  name: material

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true